### PR TITLE
Added Dynamic Campaign Graph View

### PR DESCRIPTION
**Pull request by KeithDeRuiter**
Added the ability to view the campaign entities and their relationships as a floating, dynamic graph.  View can be zoomed and panned, and the entities within can be dragged around.  It's awesome, and can be found under the campaign menu.

### CODE REVIEW

**Comment by Horatio-Blackwood** [comment]
LOL.  Awesome huh?  Yeah I played with it a bit last night.  It needs a little bit of polish in order to be complete, so I'm going to tinker with it a bit after accepting this request.

**Comment by Horatio-Blackwood** [comment]
All merged in.  I fiixed a few small bugs (missing secret relationships, didn't render minimum length licensed plates etc), added some javadoc and broke out the colors so both orbital and graph viewers could use them.

We (or I - if this is as far as you're interested in taking this) have a bit more work to do to make this a really complete, and fully usable feature.  I've got some ideas, so we can talk about it some more some time if you want.

**Comment by KeithDeRuiter** [comment]
Yeah, still a bit prototype-y, and could use some more javadoc.  I'd be down to polish it up some and add missing features though.

**Comment by Horatio-Blackwood** [comment]
Cool.  We should get together to talk about direction on this sometime.  At the bare minimum it needs to update when data changes in the primary application window.

**Pull request merged**
